//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uygulama1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cevaplar
    {
        public int CevapId { get; set; }
        public int CevapSoruId { get; set; }
        public string CevapMetin { get; set; }
        public System.DateTime CevapTarih { get; set; }
        public int CevapUyeId { get; set; }

        public virtual Sorular Sorular { get; set; }
        public virtual Uyeler Uyeler { get; set; }

    }
}
