//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uygulama1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sorular
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sorular()
        {
            this.Cevaplar = new HashSet<Cevaplar>();
        }
    
        public int SorularId { get; set; }
        public int SoruAnketId { get; set; }
        public string SoruMetin { get; set; }
        public System.DateTime SoruKayTarih { get; set; }
        public int SoruUyeId { get; set; }
        public System.DateTime SoruDuzTarih { get; set; }
        


        public virtual Anketler Anketler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cevaplar> Cevaplar { get; set; }
        public virtual Uyeler Uyeler { get; set; }
    }
}
